const products = [
    {
      id: 1,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "womens",
      image:"http://localhost:4000/images/product_1.png",
      new_price: 50.0,
      old_price: 80.5,
    },
    {
      id: 2,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "womens",
      image: "http://localhost:4000/images/product_2_copy.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 3,
      name: "Cotton Linen Saree with Subtle Checks and Designer Tassels",
      category: "womens",
      image: "http://localhost:4000/images/prachi.jpg",
      new_price: 60.0,
      old_price: 100.5,
    },
    {
      id: 4,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "womens",
      image:  "http://localhost:4000/images/product_4.png",
      new_price: 100.0,
      old_price: 150.0,
    },
    {
      id: 5,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "womens",
      image: "http://localhost:4000/images/product_5.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 6,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "womens",
      image: "http://localhost:4000/images/product_6.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 7,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "womens",
      image: "http://localhost:4000/images/product_7.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 8,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "womens",
      image:"http://localhost:4000/images/product_8.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    {
      id: 9,
      name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
      category: "womens",
      image: "http://localhost:4000/images/product_9.png",
      new_price: 85.0,
      old_price: 120.5,
    },
    // {
    //   id: 10,
    //   name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    //   category: "womens",
    //   image: "http://localhost:4000/images/product_9.png",
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 11,
    //   name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    //   category: "womens",
    //   image: "http://localhost:4000/images/product_9.png",
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 12,
    //   name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
    //   category: "womens",
    //   image:  "http://localhost:4000/images/product_9.png",
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 13,
    //   name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    //   category: "mens",
    //   image: "http://localhost:4000/images/product_9.png",
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 14,
    //   name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    //   category: "mens",
    //   image: "http://localhost:4000/images/product_9.png",
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 15,
    //   name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    //   category: "mens",
    //   image: "http://localhost:4000/images/product_9.png",
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 16,
    //   name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    //   category: "mens",
    //   image: "http://localhost:4000/images/product_9.png",
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 17,
    //   name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    //   category: "mens",
    //   image: "http://localhost:4000/images/product_9.png",
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 18,
    //   name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    //   category: "mens",
    //   image: p18_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 19,
    //   name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    //   category: "mens",
    //   image: p19_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 20,
    //   name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    //   category: "mens",
    //   image: p20_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 21,
    //   name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    //   category: "mens",
    //   image: p21_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 22,
    //   name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    //   category: "mens",
    //   image: p22_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 23,
    //   name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    //   category: "mens",
    //   image: p23_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 24,
    //   name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket",
    //   category: "mens",
    //   image: p24_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 25,
    //   name: "Boys Orange Colourblocked Hooded Sweatshirt",
    //   category: "kids",
    //   image: p25_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 26,
    //   name: "Boys Orange Colourblocked Hooded Sweatshirt",
    //   category: "kids",
    //   image: p26_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 27,
    //   name: "Boys Orange Colourblocked Hooded Sweatshirt",
    //   category: "kids",
    //   image: p27_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 28,
    //   name: "Boys Orange Colourblocked Hooded Sweatshirt",
    //   category: "kids",
    //   image: p28_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 29,
    //   name: "Boys Orange Colourblocked Hooded Sweatshirt",
    //   category: "kids",
    //   image: p29_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 30,
    //   name: "Boys Orange Colourblocked Hooded Sweatshirt",
    //   category: "kids",
    //   image: p30_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 31,
    //   name: "Boys Orange Colourblocked Hooded Sweatshirt",
    //   category: "kids",
    //   image: p31_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 32,
    //   name: "Boys Orange Colourblocked Hooded Sweatshirt",
    //   category: "kids",
    //   image: p32_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 33,
    //   name: "Boys Orange Colourblocked Hooded Sweatshirt",
    //   category: "kids",
    //   image: p33_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 34,
    //   name: "Boys Orange Colourblocked Hooded Sweatshirt",
    //   category: "kids",
    //   image: p34_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 35,
    //   name: "Boys Orange Colourblocked Hooded Sweatshirt",
    //   category: "kids",
    //   image: p35_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },
    // {
    //   id: 36,
    //   name: "Boys Orange Colourblocked Hooded Sweatshirt",
    //   category: "kids",
    //   image: p36_img,
    //   new_price: 85.0,
    //   old_price: 120.5,
    // },   
];
module.exports = products;

// const Products = [
//   {
//     id: 1,
//     name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse",
//     category: "womens",
//     image: "https://images.unsplash.com/photo-1618354691267-bf38c0a1eea2",
//     new_price: 50.0,
//     old_price: 80.5,
//   },
//   {
//     id: 2,
//     name: "Elegant Floral Midi Dress",
//     category: "womens",
//     image: "https://source.unsplash.com/600x600/?dress,women",
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 3,
//     name: "Casual Women's Shirt",
//     category: "womens",
//     image: "https://source.unsplash.com/600x600/?shirt,women",
//     new_price: 60.0,
//     old_price: 100.5,
//   },
//   {
//     id: 4,
//     name: "Formal Women's Blazer",
//     category: "womens",
//     image: "https://source.unsplash.com/600x600/?blazer,women",
//     new_price: 100.0,
//     old_price: 150.0,
//   },
//   {
//     id: 5,
//     name: "Stylish Summer Top",
//     category: "womens",
//     image: "https://source.unsplash.com/600x600/?top,women",
//     new_price: 85.0,
//     old_price: 120.5,
//   },
//   {
//     id: 6,
//     name: "Men's Slim Fit Blazer",
//     category: "mens",
//     image: "https://source.unsplash.com/600x600/?blazer,men",
//     new_price: 95.0,
//     old_price: 130.5,
//   },
//   {
//     id: 7,
//     name: "Men's T-Shirt",
//     category: "mens",
//     image: "https://source.unsplash.com/600x600/?tshirt,men",
//     new_price: 45.0,
//     old_price: 70.0,
//   },
//   {
//     id: 8,
//     name: "Men's Hooded Jacket",
//     category: "mens",
//     image: "https://source.unsplash.com/600x600/?jacket,men",
//     new_price: 110.0,
//     old_price: 160.0,
//   },
//   {
//     id: 9,
//     name: "Men's Check Shirt",
//     category: "mens",
//     image: "https://source.unsplash.com/600x600/?shirt,men",
//     new_price: 60.0,
//     old_price: 90.0,
//   },
//   {
//     id: 10,
//     name: "Kids Colorful Hoodie",
//     category: "kids",
//     image: "https://source.unsplash.com/600x600/?hoodie,kids",
//     new_price: 55.0,
//     old_price: 75.5,
//   },
//   {
//     id: 11,
//     name: "Kids Casual T-Shirt",
//     category: "kids",
//     image: "https://source.unsplash.com/600x600/?tshirt,kids",
//     new_price: 35.0,
//     old_price: 60.0,
//   },
//   {
//     id: 12,
//     name: "Kids Winter Jacket",
//     category: "kids",
//     image: "https://source.unsplash.com/600x600/?jacket,kids",
//     new_price: 75.0,
//     old_price: 95.0,
//   },
// ];

// module.exports = Products;
